---
deployment:
  tasks:
    - export DEPLOYPATH=/home/diby9755/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp -R lorovel $DEPLOYPATH